definitions:
  request.CreateClientRequestDTO:
    properties:
      birth_date:
        type: string
      health_problems:
        items:
          $ref: '#/definitions/request.CreateHealthProblemRequestDTO'
        type: array
      name:
        type: string
      sexo:
        type: string
    type: object
  request.CreateHealthProblemRequestDTO:
    properties:
      client_id:
        type: string
      grau:
        type: integer
      name:
        type: string
    type: object
  responseshttp.Causes:
    properties:
      field:
        type: string
      message:
        type: string
    type: object
  responseshttp.RestErr:
    properties:
      causes:
        items:
          $ref: '#/definitions/responseshttp.Causes'
        type: array
      code:
        type: integer
      err:
        type: string
      message:
        type: string
    type: object
  responseshttp.RestSuccess:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    name: Vinnicius Santos
  description: Backend Developer Challenger API Docs.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Backend Developer Challenger API Docs
  version: 0.0.1
paths:
  /api/v1/clients:
    post:
      consumes:
      - application/json
      description: Criar um novo cliente
      parameters:
      - description: Client
        in: body
        name: client
        required: true
        schema:
          $ref: '#/definitions/request.CreateClientRequestDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/responseshttp.RestSuccess'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responseshttp.RestErr'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responseshttp.RestErr'
      summary: Criar um novo cliente
      tags:
      - client
schemes:
- http
swagger: "2.0"
